### ISSUE TITLE
Provide isolated MW examples from AGORA

### ISSUE THREAD

**Issue by christopherlovell** [flaresimulations/synthesizer#334]
Provide some examples on high resolution isolated galaxy snapshots. [AGORA project](https://sites.google.com/site/santacruzcomparisonproject/data?authuser=0) provides many examples.

**Comment by WillJRoper** [comment]
I'm going to close this. Having dug deeper into this all the "cool" examples from the AGORA suite or similar are far too high res to be an example. The demonstrated workflow is effectively the same as any particle-based simulation so very little is gained by having the example, and any data from AGORA or other isolated sims that could be an example is so low res it's uninteresting.

Instead of an example, we can provide a demo in the docs with the output of a script run on a HPC shown within it. I'm working on this separately.

**Comment by WillJRoper** [comment]
Feel free to reopen if anyone disagrees.
