### ISSUE TITLE
Allow arbitrary masks

### ISSUE THREAD

**Issue by stephenmwilkins** [flaresimulations/synthesizer#616]
For particle based methods at the moment we can only mask with the `young` and `old` arguments. We should add an option `mask` argument that allows the use of a generic mask. I believe this simply means adding `mask` to list of arguments and then modifying `_get_mask`.

**Comment by WillJRoper** [comment]
This issue has grown to highlight a more general issue. The following is taken from slack detailing the proposed solution to clean all of this up:


- We keep young/old everywhere it is currently implemented with a deprecation warning attached.
- We add the ability to supply a mask explicitly to all methods where it makes sense to and pass this through to all generate_* methods.
- We do not implement young/old in any new methods (i.e. the lines).
- We introduce mask generators with a consistent naming convention like our spectra methods (get_mask_age , get_mask_aperture, etc.).
- We introduce a generic mask generator:
```
def get_mask(self, filter_attr, threshold, thresh_type):
    attr = getattr(self, filter_attr)
    if thresh_type == "<":
        return attr < thresh
    elif thresh_type == "<=":
        return attr <= thresh
    ...
    else:
        raise UnrecognisedArgument("WHAT ARE YOU DOING!?")
```
- We ensure that all generate_* methods produce results with the same shape irrespective of the mask (i.e. for a particle galaxy the result is always (npart, nlam) for spectra with zeros in masked out arrays. I think this is already the case but would be good to make sure. If a user doesn’t need the zeros in their end result (e.g. when an aperture is applied) they will already have the mask in hand to remove the zeros. I can see the argument coming “but that’s a waste of memory”, my response: you need this consistency when mixing things. If a user actually only cares about a subset of particles overall they should create a Galaxy or component with only this subset, this should be well documented since having consistent array shapes is a great simplifier. To enable this we should:
- Implement a get_aperture_subset method which returns a new Galaxy modifies a galaxy in place based on an aperture and a get_masked_subset which does the same for a generic mask on a component.
- We should allow get_transmission to take a mask for the same consistency reason as generate_* methods. get_transmission will then always return an array which can be applied to all entries.

**Comment by WillJRoper** [comment]
Possibly a redundant point now but there's no need for `get_transmission` to take a mask. `Sed.apply_attenuation` takes a mask and is the intended way to attenuate a spectra. Calculating a transmission should transparently adopt the shape of the input `tau_v` array.

Of course this may be superseded by the `EmissionModel` approach soon to be raised.
